---
- name: Install NVM
  hosts: localhost
  vars:
    nvm_version: 0.40.1

  tasks:
    - name: Download and install NVM
      ansible.builtin.shell: |
        set -o pipefail
        "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash"
      args:
        creates: /home/danny/.nvm/nvm.sh
      register: output
      changed_when: output.rc != 0

    - name: Add NVM source line to .bashrc
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker_begin: "BEGIN NVM"
        marker_end: "END NVM"
        append_newline: true
        prepend_newline: true
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    - name: Source NVM script
      ansible.builtin.shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install node
      args:
        executable: /bin/bash
      register: output
      changed_when: output.rc != 0
